### PR TITLE
Links to Arch Linux AUR packages

### PR DESCRIPTION
**Pull request by psyriccio**
Added links to mandelbulber2 Arch Linux AUR packages

### CODE REVIEW

**Comment by psyriccio** [comment]
Changes in README.md can not broke code building

**Comment by zebastian** [comment]
Hi @psyriccio,

You are obviously right, will merge.

Thanks for maintaining mandelbulber on arch!

**Comment by psyriccio** [comment]
@zebastian, thanks to amazing fractal tool! I`d like to help, Arch Linux users cant stay without Mandelbulber any more )))

**Comment by mancoast** [comment]
Hello,

I deeply respect arch-linux and am very thrilled to see mandelbulber inclusion.

Thanks,
coast

**Comment by psyriccio** [comment]
Yea! A prebuilded packages are available here http://jws.forteholding.ru/mandelbulber2/
(but 32-bit version wasnt auto-builded this time, i`d build it by hand at monday.
till one of these days, I'll add the prebuilded packages in my mirror of arch linux repo
http://jws.forteholding.ru/archlinux/

but actually he is quickly builds from the AUR

**Comment by zebastian** [comment]
@psyriccio I only take a spoonful of credit, the rest goes to the others in the team :)
It is really exciting to see people including mandelbulber in the big package repositories.

I am curious: How is the workflow / infrastructure under arch linux?
I know the debian view of things a little bit: 
- the package has to be prepared to fit the debian build system with gcc
- then these get build for different cpu arches and published on all download mirrors
- there are a couple of steps in the package life cycle (from experimental > testing > unstable > ...)
- people specify their mirrors and apt-get install their favourite packages

Is this also the way arch handles this, or are there any big differences?

**Comment by psyriccio** [comment]
@zebastian First, any package is added to the AUR.
AUR is very similar to the FreeBSD ports-system, it is such a large repository of build scripts. User, for example, executes "yaourt -S mandelbulber2", ​​-- build script will be downloaded, source code, and all you need to build will also be downloaded, Everything is automatically compiled and packed in a package that is immediately installed in the system.
Users vote (directly during installation) for the packages from AUR and some of them are included into one of the official binary repositories (core, community or extra). Already as a binary package, but technically everything is like in AUR, simply binary package availble without "building". But nothing prevents to make a binary, the unofficial repository, in order that-be to provide pre-compiled packages.

for example, build script of mandelbulber package
[mandelbulber2.PKGBUILD.txt](https://github.com/buddhi1980/mandelbulber2/files/614614/mandelbulber2.PKGBUILD.txt)

**Comment by zebastian** [comment]
Thanks for the explanation.
The mandelbulber2.PKGBUILD.txt looks short and nice :)
If there is anything about the code we can change to make it easier / better / cooler to integrate with arch let us know.
I like the part about voting for the packages in order to decide the repository priority. I think that part is missing in other linux repositories.

**Pull request merged**
