### PR TITLE
EXR Support for rendered images

### PR DESCRIPTION
**Pull request by zebastian**
Before merge, please check Windows compatibility.

RGB, A and Z component can be saved individually.
Image format well suited for blender.

needs package libopenexr-dev
ugly path in .pro file needs to be fixed

### CODE REVIEW

**Comment by buddhi1980** [comment]
I can't compile libilm. It stucks in compilation of 'half'. I have no idea
how to solve it. I got following errors:

Making all in Half
make[1]: Wejście do katalogu
'/home/krzysztof/Roboczy/exr/ilmbase-1.0.1/Half'
make  all-am
make[2]: Wejście do katalogu
'/home/krzysztof/Roboczy/exr/ilmbase-1.0.1/Half'
if /bin/bash ../libtool --tag=CXX --mode=compile i686-w64-mingw32-g++
-DHAVE_CONFIG_H -I. -I. -I../config -I../config  -I/usr/include/OpenEXR
-pipe -g -O2 -pthread -MT half.lo -MD -MP -MF ".deps/half.Tpo" -c -o
half.lo half.cpp; \
then mv -f ".deps/half.Tpo" ".deps/half.Plo"; else rm -f ".deps/half.Tpo";
exit 1; fi
 i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I. -I../config -I../config
-I/usr/include/OpenEXR -pipe -g -O2 -pthread -MT half.lo -MD -MP -MF
.deps/half.Tpo -c half.cpp  -DDLL_EXPORT -DPIC -o .libs/half.o
half.cpp:64:1: error: expected primary-expression before 'const'
 const unsigned short half::_eLut[1 << 9] =
 ^
half.cpp:91:1: error: expected ',' or ';' before 'short'
 short
 ^
Makefile:324: polecenia dla obiektu 'half.lo' nie powiodły się
make[2]: *** [half.lo] Błąd 1
make[2]: Opuszczenie katalogu
'/home/krzysztof/Roboczy/exr/ilmbase-1.0.1/Half'
Makefile:223: polecenia dla obiektu 'all' nie powiodły się
make[1]: *** [all] Błąd 2
make[1]: Opuszczenie katalogu
'/home/krzysztof/Roboczy/exr/ilmbase-1.0.1/Half'
Makefile:283: polecenia dla obiektu 'all-recursive' nie powiodły się
make: *** [all-recursive] Błąd 1


2015-05-25 11:31 GMT+02:00 Sebastian Jennen <notifications@github.com>:

**Comment by zebastian** [comment]
The corresponding code in half.CPP looks quite  weird: 
https://github.com/openexr/openexr/blob/master/IlmBase/Half/half.cpp
Its some kind of Makro inlining the conversion code, instead of inlining with cpp.
So the precompiler fails in any way, and produces broken code.
Can you get anymore output, or  the precompiled code?

**Comment by buddhi1980** [comment]
I have passed through errors in compiling half.cpp (some tricks with
generating eLut.h and toFloat.h where are some lookup tables). But then I
have stuck in compilation of IlmThreadPool.cpp

Now I got:

i686-w64-mingw32-g++ -shared -nostdlib
/usr/lib/gcc/i686-w64-mingw32/4.9-win32/../../../../i686-w64-mingw32/lib/../lib/dllcrt2.o
/usr/lib/gcc/i686-w64-mingw32/4.9-win32/crtbegin.o  .libs/IlmThreadPool.o
.libs/IlmThread.o .libs/IlmThreadSemaphore.o .libs/IlmThreadMutex.o
.libs/IlmThreadPosix.o .libs/IlmThreadSemaphorePosix.o
.libs/IlmThreadSemaphorePosixCompat.o .libs/IlmThreadMutexPosix.o
 ../Iex/.libs/libIex.dll.a -L/usr/lib/gcc/i686-w64-mingw32/4.9-win32
-L/usr/lib/gcc/i686-w64-mingw32/4.9-win32/../../../../i686-w64-mingw32/lib/../lib
-L/usr/lib/gcc/i686-w64-mingw32/4.9-win32/../../../../i686-w64-mingw32/lib
-lstdc++ -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -ladvapi32
-lshell32 -luser32 -lkernel32 -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex
-lmsvcrt /usr/lib/gcc/i686-w64-mingw32/4.9-win32/crtend.o  -pthread
-pthread -o .libs/libIlmThread-6.dll -Wl,--image-base=0x10000000
-Wl,--out-implib,.libs/libIlmThread.dll.a
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x45): undefined reference
to `IlmThread::Thread::Thread()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x68): undefined reference
to `IlmThread::Thread::start()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x84): undefined reference
to `IlmThread::Thread::~Thread()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0xfb): undefined reference
to `IlmThread::Semaphore::post()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x10f): undefined reference
to `IlmThread::Semaphore::wait()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x27a): undefined reference
to `IlmThread::Semaphore::Semaphore(unsigned int)'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x2d3): undefined reference
to `IlmThread::Semaphore::wait()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x2e4): undefined reference
to `IlmThread::Semaphore::~Semaphore()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x300): undefined reference
to `IlmThread::Semaphore::~Semaphore()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x351): undefined reference
to `IlmThread::Semaphore::wait()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x385): undefined reference
to `IlmThread::Semaphore::post()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x3ee): undefined reference
to `IlmThread::Semaphore::Semaphore(unsigned int)'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x405): undefined reference
to `IlmThread::Mutex::Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x43e): undefined reference
to `IlmThread::Semaphore::Semaphore(unsigned int)'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x455): undefined reference
to `IlmThread::Mutex::Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x48e): undefined reference
to `IlmThread::Mutex::Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x4c9): undefined reference
to `IlmThread::Mutex::~Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x4e8): undefined reference
to `IlmThread::Semaphore::~Semaphore()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x526): undefined reference
to `IlmThread::Mutex::~Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x560): undefined reference
to `IlmThread::Semaphore::~Semaphore()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x619): undefined reference
to `IlmThread::Mutex::~Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x641): undefined reference
to `IlmThread::Mutex::~Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x655): undefined reference
to `IlmThread::Semaphore::~Semaphore()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x67d): undefined reference
to `IlmThread::Mutex::~Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x68e): undefined reference
to `IlmThread::Semaphore::~Semaphore()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x6e4): undefined reference
to `IlmThread::Mutex::~Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x722): undefined reference
to `IlmThread::Mutex::~Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x741): undefined reference
to `IlmThread::Semaphore::~Semaphore()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x77f): undefined reference
to `IlmThread::Mutex::~Mutex()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x79b): undefined reference
to `IlmThread::Semaphore::~Semaphore()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x823): undefined reference
to `IlmThread::Semaphore::post()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x830): undefined reference
to `IlmThread::Semaphore::wait()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x1098): undefined reference
to `IlmThread::Semaphore::post()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text+0x1644): undefined reference
to `IlmThread::Thread::~Thread()'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text$_ZN9IlmThread4LockC1ERKNS_5MutexEb[__ZN9IlmThread4LockC1ERKNS_5MutexEb]+0x2c):
undefined reference to `IlmThread::Mutex::lock() const'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text$_ZN9IlmThread4LockD1Ev[__ZN9IlmThread4LockD1Ev]+0x1c):
undefined reference to `IlmThread::Mutex::unlock() const'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text$_ZN9IlmThread4Lock7acquireEv[__ZN9IlmThread4Lock7acquireEv]+0x11):
undefined reference to `IlmThread::Mutex::lock() const'
.libs/IlmThreadPool.o:IlmThreadPool.cpp:(.text$_ZN9IlmThread4Lock7releaseEv[__ZN9IlmThread4Lock7releaseEv]+0x11):
undefined reference to `IlmThread::Mutex::unlock() const'
collect2: error: ld returned 1 exit status

I'm not sure if it's possible to compile it with mingw. In readme I can see
that it's mostly prepared for Visual C++. I give up with with Windows
version. But we still can do EXR support for Linux version.


2015-06-08 22:42 GMT+02:00 Sebastian Jennen <notifications@github.com>:

**Comment by buddhi1980** [comment]
What to think to implement EXR in similar way to gamepad support?
You can add some condition in mandelbulber.pro file whic will check if /usr/include/OpenEXR folder exists in the system. If yes, it can define some macro variable. Then in the program if #ifdefs you can enable this feature.
This would be the way which will make the less pain for users which want to compile the program.

**Pull request closed without merging**
