### PR TITLE
CMake: refactor install

### PR DESCRIPTION
**Pull request by lachs0r**
Make it comply with *nix conventions and allow relative data path,
e.g. for AppImage and Windows builds.
Avoid having symlinks in the repository. CMake does not follow them
and they’re poorly supported on Windows.

See #336.

### CODE REVIEW

**Comment by buddhi1980** [comment]
@zebastian , can you take care about this pull request?
Check if qmake will still properly (SHARED_DIR is no longed declared by default).

**Comment by lachs0r** [comment]
It might not work properly anymore. Sorry about that. I only took care of one of three build systems.

**Comment by buddhi1980** [comment]
I think you can keep symbolic links for another build systems (I havent observed any problems with symlinks under Windows) and also keep default definition of  SHARED_DIR (or let us know if it makes problem)
By the way, main build system for this project is qmake, so any changes has to be applied to .pro files, too.
It's good idea to move documentation from /usr/share/mandelbulber/doc to /usr/share/doc/mandelbulber

**Comment by lachs0r** [comment]
The symlinks cause trouble with the CMake install step. It does not follow or update them, and I’d have to maintain a list of subdirectories to be installed to be sure that it works. Not a huge problem, but I thought I’d just avoid the problem altogether.

I have restored the default definition of `SHARED_DIR`.

**Comment by zebastian** [comment]
@lachs0r qmake is broken due to missing formula folder symlink (maybe more erros, this is the first one i got from building from https://github.com/lachs0r/mandelbulber2)
I like your changes, but can you break this into smaller commits, and at the same time keep the builds of other make prerocessors (qmake, msvc) stable?

**Comment by lachs0r** [comment]
Will do.

**Comment by zebastian** [comment]
great, thank you

**Comment by mancoast** [comment]
@zebastian I will merge and fix, lets get @lachs0r's first commit in the code base.

**Comment by archenroot** [comment]
Hi guys, any progress? last try failed, I am waiting for this CMake support to adopt into Gentoo.

**Comment by mancoast** [comment]
What are you seeing when you attempt the build for gentoo?  The cmake build
works for k1om build/install on centos.

**Comment by zebastian** [comment]
I think, i know what the problem is.
I will try to fix it this evening...

**Comment by zebastian** [comment]
@archenroot there was a missing include for cmake, i added it in latest commit: https://github.com/buddhi1980/mandelbulber2/commit/3617e92506428c2f059e3e42575939d8aa00814f
can you try again?

**Pull request merged**
