### PR TITLE
Upgrade build files for linking with OpenEXR 3

### LINKED ISSUE #900: Does not compile with OpenEXR 3
With OpenEXR 3, the current methods of linking in both qmake and cmake are no longer functional. Libraries have been renamed, etc. Fortunately it doesn't seem like there are any code changes required.

### PR DESCRIPTION
**Pull request by cagelight**
Resolves #900
This is my fix for it, I tested both build paths and everything seems to work great.

### CODE REVIEW

**Comment by buddhi1980** [comment]
Will your patch keep backward compatibility (with EXR 2)?

**Comment by cagelight** [comment]
Honestly I am not sure, and I don't have an easy way to test that in my current setup. That said, both methods now rely solely on pkg-config, which should provide stable behavior between OpenEXR 2 and 3. I would be surprised if it didn't work.

**Comment by buddhi1980** [comment]
I will try it. In case if it doesn't work, I will revert changes.

**Comment by buddhi1980** [comment]
Works file with EXR 2.5.7. Thank you for the patch.

**Pull request merged**
