### PR TITLE
[WIP] Fix paths in *.fract files to SHARED_PATH

### PR DESCRIPTION
**Pull request by KoviRobi**
WIP: It doesn't seem to work (compiling as a NixOS package), perhaps `$$ROOT/deploy/patch-examples.sh` isn't the right path

This currently only works for unix
- Uses gettext's envsubst (added to deploy/README requirements)
- Patches using deploy/patch-templates.sh, for *.template files
- Moved *.fract files requiring patching to *.fract.template

The following files have paths in them that I didn't know how to patch:
- Graeme McLaren  collection - license Creative Commons  (CC-BY 4.0)/mandelbulb_eye 001.fract
- Robert Pancoast collection - license Creative Commons (CC-BY 4.0)/box-deuce-deuce.fract
- Robert Pancoast collection - license Creative Commons (CC-BY 4.0)/menger-fatbackstrokin.fract
- mandelbox_menger_with_textures.fract
- monte carlo global illumination.fract

(From a grep -rl '[A-Z]:\\\|/home\|/usr' deploy/share/mandelbulber2/,
there might be more.)

### CODE REVIEW

**Comment by buddhi1980** [comment]
What about instalation of Mandelbulber on Windows?

**Comment by KoviRobi** [comment]
I do not know how to do this on Windows (and a bit unclear, do you use qmake for Windows too?)

**Comment by KoviRobi** [comment]
It also currently installs the *.fract.template files, not just the *.fract files, not sure how to get around that.

**Comment by KoviRobi** [comment]
Closing in favour of #731

**Pull request closed without merging**
