### PR TITLE
Add CLI option "silentOption" to silently exit without user prompt.

### PR DESCRIPTION
**Pull request by mancoast**
This is useful for shell scripting.

### CODE REVIEW

**Comment by mclarekin** [comment]
Thanks Mancoast for helping with Mandelbulber, I am not a  programmer so I
have no understanding of what you are doing, but I can tell from Buddhi's
responses that you are doing some good things.

**Comment by buddhi1980** [comment]
@mancoast, I got the same question in my head as @zebastian . I'm not sure what is the purpose of this option. Could you give us an example in what case this option is needed? Maybe it's helpful, but we cannot see this yet. By the way, thank you for your involvement.

**Comment by mancoast** [comment]
Hello,

Its been a fun reading this code-base and viewing all the artwork.

I use many different fractal files and render folders for animations when experimenting with parameters.
While shell scripting, I have accidentally deleted previously rendered data.
I like to have the silent exit CLI option to ensure that under any circumstances there exists a fail-safe.
Scripts can sometimes have unexpected consequences while still hammering out the details.
These changes prevent accidental deletion of data during times of un-expected behavior.

Thanks,
coast

**Comment by buddhi1980** [comment]
Merged

**Pull request merged**
