### PR TITLE
Arch-bin-repo readme

### PR DESCRIPTION
**Pull request by psyriccio**
Adding info about Arch Linux prebuilded binary packages installation to readme

### CODE REVIEW

**Comment by zebastian** [comment]
hi psyriccio, 

wont merge, since this introduces private repository dependencies.

**Comment by psyriccio** [comment]
Arch Linux -- good software, like a mandelbulber. It is a very good idea to provide an binary package for it. I can build it and send/upload in another place, or write a package build script this "repo" is a simple "shared directory" at my work. If you have some "more good" place -- a can help with package. package size with last mandelbulber release is ~30 Mb  BRg!

**Comment by zebastian** [comment]
I can host it on cdn.mandelbulber.org, if you others agree?

**Comment by buddhi1980** [comment]
If you prepare (compile) binaries on trusted machine, then I agree. But is your computer trusted? In Linux world there is the rule to not distribute (or download) binaries which are not trusted. If it's not achievable, then only sorce code should be distributed. Some years ago I have distributed binaries for mandelbulber, but then I have learnt that many users asked me if my computer is trusted to prepare binaries. I didn't know what to answer. 
For instant packages for Debian are compiled by Debian's maintainer, who use trusted servers hosted by Debian. I do not deliver any binaries to Debian's maintainers.
This the reason why Linux is so safe to use.

**Comment by zebastian** [comment]
Thats not only the single point of failure:
My server can of course be compromised. Unlikely but possible.
Anyway, if we have a way to get a reproducable build i can host it...

**Comment by mancoast** [comment]
@zebastian does your motherboard support TPM for use of cryptology?

**Comment by zebastian** [comment]
I dont know? how do i find this out? what is it for?

**Comment by mancoast** [comment]
An international standard for a secure cryptoprocessor
- https://en.wikipedia.org/wiki/Trusted_Platform_Module

**Comment by psyriccio** [comment]
I can help to prepare build environment for building arch package (scripts, qemu-image or lxc/docker container maybe...) such as bash-script which builds arch-environment in a docker container, using only official archlinux repository and package builing script which builds a package in this environment using sources from mandelbulber git repo.

**Pull request closed without merging**
