### PR TITLE
azure foundation

### PR DESCRIPTION
**Pull request by coast77777777777**
these files collected from openexr repo
@buddhi1980 this might help get our software into the VFX industry

### CODE REVIEW

**Comment by buddhi1980** [comment]
Can you tell me more about it? How it will help with VFX?
Why there files need to be in share folder in root repository folder?

**Comment by coast77777777777** [comment]
This is a move towards using the same system standards as the academy software foundation. Ideally, we support the industry standards in our system for others to easily understand and adopt this fractal system into their workflows.

**Comment by buddhi1980** [comment]
Is this something like appveyour or TravisCL? If you can tell me more details.
You haven't answered my question about new share folder.

**Comment by coast77777777777** [comment]
Greetings K,

In essence azure pipelines is another continuous integration service like Appveyor or Travis. 
The specific folders and file locations are subject to the standards of the foundation, however we are not members of the foundation so we can arrange the files anyway we want. 
I would like to be fully compliant with the ASWF standards by keeping everything up to the specified level. More details are available here: https://www.aswf.io/about/
What are your thoughts?
Thanks,
Coast

When Microsoft bought GitHub a while back, they modernized Microsoft Azure pipelines to work with GitHub for free with open-source projects.

**Comment by buddhi1980** [comment]
Can we move this share directory to azure/share?
I want this change because for all Linux users share directory will be very confusing
After this change I will pull this code and try configure it on GitHub

**Comment by coast77777777777** [comment]
Ok that’s a good strategy. I will send another commit in a few minutes. IMO The azure pipelines seemed way overly complicated with configuration for my fork, so prepare to read some M$ documentation.

**Comment by buddhi1980** [comment]
Can I pull it tomorrow after 2.19 will be released?

**Comment by coast77777777777** [comment]
Yea that’s a good plan.

**Comment by buddhi1980** [comment]
Azure Pipelines is already installed in our repository

**Pull request merged**
