### PR TITLE
ui changes for cmake

### PR DESCRIPTION
**Pull request by mancoast**
the cmake build system generates the ui_dock_animation, ui_dock_animation, and ui_dock_queue files in the build folder with other  CMakeFiles

### CODE REVIEW

**Comment by buddhi1980** [comment]
I'm not going to approve this change. For all another systems where there is used qmake with make, this file is located in mandelbulber/qt folder. Please modify cmake files to have this file in the same location as for standard qmake.

**Comment by buddhi1980** [comment]
@zebastian , could you support this topic? As I know there have to be some solution for cmake, because it already works for material_editor.ui

**Comment by buddhi1980** [comment]
@mancoast thanks for reporting this problem. Even if you proposed wrong solution, now I see why Appveyor shows the problem.

**Comment by mancoast** [comment]
The root cause of compilation failure is the relative path of the includes.
`#include "../qt/ui_dock_animation.h"`
The ui_*.h files do not exist in the `../qt/` folder for cmake builds.

Is it possible to add a compiler include argument for the `../qt/` folder in the qmake project?
Then we could use `#include "ui_dock_animation.h"` for both cmake and qmake.

**Comment by buddhi1980** [comment]
@mancoast, your solution is very good. I have just implemented it. Please let me know it it works properly with cmake.

**Comment by zebastian** [comment]
first build with appveyor (cmake and msvc) is now fixed, so the problem is resolved:
https://ci.appveyor.com/project/zebastian/mandelbulber2-s84yl
well done!

**Comment by mancoast** [comment]
tested and confirmed resolved.

**Pull request closed without merging**
