### PR TITLE
Optimize isNaN performance

### PR DESCRIPTION
**Pull request by mancoast**
use std::isnan

### CODE REVIEW

**Comment by buddhi1980** [comment]
It would be too easy. Is it works with -ffastmath gcc flag?

**Comment by mancoast** [comment]
Broken on OSX, Requires further investigation.

**Comment by mancoast** [comment]
#include <math.h>
-->
http://en.cppreference.com/w/c/numeric/math/isnan

use ::isnan instead of std::isnan

**Comment by buddhi1980** [comment]
Read this http://stackoverflow.com/questions/22931147/stdisinf-does-not-work-with-ffast-math-how-to-check-for-infinity
Then you will know why I have used my own solution. It is still faster to check NaN which this function than to not use -ffast-math nad use standard NaN detection

**Comment by mancoast** [comment]
http://en.cppreference.com/w/cpp/numeric/math/isnan

looks like std:isnan compiles for OSX and when the the follow two conditions met:
1.) include the cmath header
2.) C++11 standard being used

I have personally tested this solution on GNU linux and ICC linux.

**Comment by buddhi1980** [comment]
How you have tested? Is it really detects NaN when -ffast-math is used?

Try this code to test it:
```
	double x = -1.0;
	x = x / (x + 1.0);
	x += 10.0;
	x = sin(x);
	qDebug() << x;
	qDebug() << std::isnan(x);
```
I getting this output:
```
Debug: nan
Debug: false
```
As you see result of std::isnan(x) is false.
I use following g++ flags:  -march=native -msse2 -ffast-math

**Comment by mancoast** [comment]
It looks like the combination of std::isnan and -ffast-math carries unmitigated risk.
Instead lets test the gsl implementation of isNaN.

**Comment by mancoast** [comment]
Hello,

Attached is the extensive log for the gsl_isnan performance on x86_64 using g++ and k1om using icpc.
[mandelbulber2-NaNtester-20160903180058.txt](https://github.com/buddhi1980/mandelbulber2/files/453657/mandelbulber2-NaNtester-20160903180058.txt)


The results for gsl look very promising.
Please consider this sample of the results:
```

Test for NaN cases:
double x = -1.0; x = x / (x + 1.0); x += 10.0; x = sin(x);
x	-nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
NaNs:


x	-0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0


x	0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan*-0 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan/-0 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan+0 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan-0 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan*0 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan/0 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan+-1 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan--1 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan*-1 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan/-1 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan+1 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan-1 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan*1 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan/1 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan+inf = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan-inf = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan*inf = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan/inf = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan+-inf = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan--inf = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan*-inf = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan/-inf = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan+3.6452e-4951 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan-3.6452e-4951 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan*3.6452e-4951 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan/3.6452e-4951 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan+-3.6452e-4951 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan--3.6452e-4951 = nan


x	nan
std::isnan(x);	1
::isnan(x);	1
gsl_isnan(x);	1
nan*-3.6452e-4951 = nan
```

Additionally, the use of gsl_isnan decreases the amount of instructions retired to the isNaN operations.

Screenshot Before:
screenshot from 2016-08-01 20-31-49

Screenshot After:
screenshot from 2016-09-03 18-00-06

**Comment by buddhi1980** [comment]
Thank you! gsl_isnan() works perfect with -ffast_math ! By the way the best will be to use !gsl_finite() which gives information about infinite and NaN at one call.

**Comment by mancoast** [comment]
Results using  !gsl_finite() attached.

[mandelbulber2-NaNtester-20160904140746.txt](https://github.com/buddhi1980/mandelbulber2/files/454043/mandelbulber2-NaNtester-20160904140746.txt)

Code Profiler shows that gsl_finite retires even fewer instructions.
screenshot from 2016-09-04 14-06-44


```

	Test for NaN cases:
double x = -1.0; x = x / (x + 1.0); x += 10.0; x = sin(x);
x	-nan
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	1
NaNs:


x	-0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	-nan
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	1
!gsl_finite(x)	1
-0/-0 = -nan


x	0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	-0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	-0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	-nan
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	1
!gsl_finite(x)	1
-0/0 = -nan


x	-1
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	1
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	1
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	-1
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	-0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	-0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	inf
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	1


x	-inf
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	1


x	-nan
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	1
!gsl_finite(x)	1
-0*inf = -nan


x	-0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


x	-inf
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	1


x	inf
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	1


x	-nan
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	1
!gsl_finite(x)	1
-0*-inf = -nan


x	0
std::isnan(x);	0
::isnan(x);	0
gsl_isnan(x);	0
!gsl_finite(x)	0


```

**Pull request merged**
