### PR TITLE
Added ability to export meshes.

### PR DESCRIPTION
**Pull request by sadaszewski**

### CODE REVIEW

**Comment by zebastian** [comment]
hi  sadaszewski, thats a cool feature!

This makes volume rendering way more easier, than the current workflow with the slices.
We cannot merge your pull request right now, since you modified files, which should rather stay as they are:
 CMakeLists.txt (here you hardcoded paths, which should better be in non project config, like path environment variable, ...)
README.md (here you deleted the previous content)
Also the two dialogs for volume slice and mesh export are pretty much alike, it would be nicer for the user to unify into one export dialog with a switch for [ply / slices png]
Otherwise you really kept good to the coding standard.
Can you / Do you want to make the changes and reopen another pull request?
I can also help you with this, if you want to.
You can also contact me at sebastian.jennen@gmx.de

Thanks!

**Comment by buddhi1980** [comment]
It's very interesting code. Before we merge this code, there have to be corrected issues mentioned by @zebastian. 
I have the question about source of code for python marching cubes. Is it your code, or it's taken from here http://scikit-image.org/docs/dev/auto_examples/plot_marching_cubes.html ?
If it is third party code, then there have to be checked all licensing conditions.

**Comment by sadaszewski** [comment]
Hi guys,

Thanks for the fast reply.

The PyMCubes code is from here: https://github.com/
pmneila/PyMCubes/tree/master/mcubes/src - it's BSD-licensed.

How would you like to address the other issues? IMHO separate dialog is
quite a user-friendly solution and an approach that I've observed in many
modern applications, e.g. 3D Coat, Blender - reliance on the menu system to
find WHAT you want to do and have the dialog to specify HOW you want to do
it. I tend to believe that voxel export and mesh export are different
enough to be treated as two different things although they share same
settings. Plus it gives space for any further divergence in settings which
I strongly expect to happen.

You might be interested in my blog entry on this: http://algoholic.eu/
export-meshes-from-mandelbulber/  - there's a rendering from Blender and
I'll be placing more details there in the future.

It's just a start - lots of improvements need to happen to that code. I'd
equally like to thank you for the work on Mandelbulber - it's a great piece
of software.

Best,

S.

**Comment by mclarekin** [comment]
I took a look, cool!

**Comment by zebastian** [comment]
hi  @sadaszewski,

you convinced me about the new dialog. Keep it that way, later i will try to superclass common functionality, but in the first place your changes are good as they are.
BSD clause 3 should be incorporatable with GPL. BTW you must be willing to accept the gpl license for your changes as well. (I hate this license stuff)
so when you revert the changes for 
CMakeLists.txt 
README.md
and reopen a pull request, you should be good to go for a merge.

You can also write a line in the README about ply export functionality.
Also feel free to give yourself proper acknowledgement (About Mandelbulber Dialog) if you want to.
We will fully incorporate your new files, meening there is a script which will autoformat your changes and put in the default mandelbulber header (The one with the mandelbulb in ASCII art).

If thats all fine with you i would be glad if we can include the ply export functionality!

**Comment by sadaszewski** [comment]
Happy to hear that. I'll finish it this or early next week.

Best,

S.

**Comment by sadaszewski** [comment]
New pull request issued. It works better now using distance to interpolate
geometry positioning not just the blocky 0/1 voxel export. Gives beautiful
images👍

Best,

S.

**Pull request closed without merging**
